### ISSUE TITLE
load faild after install triton

### ISSUE THREAD

**Issue by czcz1024** [kijai/ComfyUI-HunyuanVideoWrapper#100]
a few days ago,i have run success with trion.
i don't know which nodes update make some error.

Traceback (most recent call last):
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 853, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "D:\ai\ComfyUI\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\auto.py", line 21, in <module>
    from .bitsandbytes import BnB4BitDiffusersQuantizer, BnB8BitDiffusersQuantizer
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes\__init__.py", line 2, in <module>
    from .utils import dequantize_and_replace, dequantize_bnb_weight, replace_with_bnb_linear
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\quantizers\bitsandbytes\utils.py", line 32, in <module>
    import bitsandbytes as bnb
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\__init__.py", line 15, in <module>
    from .nn import modules
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn\__init__.py", line 21, in <module>
    from .triton_based_modules import (
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\nn\triton_based_modules.py", line 6, in <module>
    from bitsandbytes.triton.dequantize_rowwise import dequantize_rowwise
  File "D:\ai\ComfyUI\python\lib\site-packages\bitsandbytes\triton\dequantize_rowwise.py", line 12, in <module>
    import triton
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 43, in _discover_backends
    compiler = _load_module(name, os.path.join(root, name, 'compiler.py'))
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\ai\ComfyUI\python\lib\site-packages\triton\backends\amd\compiler.py", line 2, in <module>
    from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 12, in <module>
    from .hyvideo.modules.posemb_layers import get_nd_rotary_pos_embed
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\__init__.py", line 1, in <module>
    from .models import HYVideoDiffusionTransformer, HUNYUAN_VIDEO_CONFIG
  File "D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 8, in <module>
    from diffusers.models import ModelMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 843, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ai\ComfyUI\python\lib\site-packages\diffusers\utils\import_utils.py", line 855, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.modeling_utils because of the following error (look up to see its traceback):
DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

Cannot import D:\ai\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper module for custom nodes: Failed to import diffusers.models.modeling_utils because of the following error (look up to see its traceback):
DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。

when i uninstrall trion,it's ok,the node import success,
please help thx

**Comment by 4lt3r3go** [comment]
looks like the same issue to me:
https://github.com/kijai/ComfyUI-HunyuanVideoWrapper/issues/92

**Comment by osagem** [comment]
It should be triton windows problem.
[https://github.com/woct0rdho/triton-windows/issues/26#issuecomment-2532088383](url)

**Comment by osagem** [comment]
err fix done.
file msvcp140.dll is not copied properly.

https://github.com/woct0rdho/triton-windows?tab=readme-ov-file#test-if-it-works
`Copy-paste msvcp140.dll, vcruntime140.dll, and vcruntime140_1.dll from C:\Windows\System32\ to the folder containing python.exe
`
https://github.com/woct0rdho/triton-windows/issues/26#issuecomment-2532565733

**Comment by Huyanxiao** [comment]
from triton._C.libtriton import ir, passes, llvm, amd
ImportError: DLL load failed while importing libtriton: 动态链接库(DLL)初始化例程失败。
解决方案：不能使用triton-3.0.0-cp312-cp312-win_amd64.whl，将python降级到3.1，然后安装triton-2.1.0-cp310-cp310-win_amd64.whl之后问题解决

**Comment by 1pedroeblo** [comment]
Make sure you have Visual Studio Desktop Development C++ installed and Python also, plus Python added in path. Not sure if python itself needed, since it's installed locally near ComfyUI folder. But that helped me. I was able to run successfully sageattention
