### ISSUE TITLE
DownloadAndLoadHyVideoTextEncoder - '.to' is not supported for '4-bit' or '8-bit' bitsandbytes models.

### ISSUE THREAD

**Issue by adamreading** [kijai/ComfyUI-HunyuanVideoWrapper#140]
Hi - everything was working fine - I use the Quant in the text encoder with bn4 - and it speeds up my process by about 10x...

I finished a new workflow and did the gitpull to the latest versions and updated all the nodes. But when running withe the quant on it fails every time. Where is was taking 40 seconds a run pre the update it snow 300-400 seconds with the Quant off...
[crash  Hunyuan.txt](https://github.com/user-attachments/files/18132271/crash.Hunyuan.txt)

Loving your work

**Comment by kijai** [comment]
Did you update transformers and accelerate to the latest too?

**Comment by adamreading** [comment]
Ahh - I didn't know that was required - I'll try and work out how I can do that on the Cloud server - with triton it was as easy as putting Triton in the pip install section of comfyui manager - fingers crossed that works the same

**Comment by kijai** [comment]
> Ahh - I didn't know that was required - I'll try and work out how I can do that on the Cloud server - with triton it was as easy as putting Triton in the pip install section of comfyui manager - fingers crossed that works the same
> 

Me neither until recently, probably should just put them in requirements, even if I still don't really want to out bitsandbytes there as it at least used to cause issues for some people.

**Comment by adamreading** [comment]
I tried to update transformers and killed my instance again lol - ttributeError: module 'decoders' has no attribute 'DecodeStream'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/app/main.py", line 91, in <module>
    import execution
  File "/data/app/execution.py", line 13, in <module>
    import nodes
  File "/data/app/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/data/app/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/data/app/comfy/sd.py", line 21, in <module>
    from . import model_detection
  File "/data/app/comfy/model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "/data/app/comfy/supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "/data/app/comfy/sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback):
module 'decoders' has no attribute 'DecodeStream'

**Comment by kijai** [comment]
> > issues
> 
> So should I be updating Bitsnbytes - or just accelerate and transformers?
> 

It works for me with all of those at current latest version, with torch 2.5.1.

**Comment by adamreading** [comment]
Hi Kijai - i updated xformers / torchaudio / torchvision / accelerate - torch is at 2.5.1 - but same error when running the bitsnbytes.
[Hunyuan crash2.txt](https://github.com/user-attachments/files/18135088/Hunyuan.crash2.txt)
