### ISSUE TITLE
`video_length-1` must be a multiple of 4, got 20

### ISSUE THREAD

**Issue by mostafablender** [kijai/ComfyUI-HunyuanVideoWrapper#143]
HI  i used your same example video but get this error 
i have rtx 4080 with 16 vram 
what should i do to get video 2 video  ? 

my log is : 

Prompt executed in 36.32 seconds
got prompt
encoded latents shape torch.Size([1, 16, 5, 18, 32])
!!! Exception during processing !!! `video_length-1` must be a multiple of 4, got 20
Traceback (most recent call last):
  File "E:\SSSSSSSSSPC\ComfyUI_windows_portable2\ComfyUI_windows_portable2\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SSSSSSSSSPC\ComfyUI_windows_portable2\ComfyUI_windows_portable2\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SSSSSSSSSPC\ComfyUI_windows_portable2\ComfyUI_windows_portable2\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\SSSSSSSSSPC\ComfyUI_windows_portable2\ComfyUI_windows_portable2\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SSSSSSSSSPC\ComfyUI_windows_portable2\ComfyUI_windows_portable2\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 914, in process
    raise ValueError(
ValueError: `video_length-1` must be a multiple of 4, got 20

Prompt executed in 2.50 seconds

**Comment by p80ric** [comment]
also got cofused by this. seems like it must have 101 frames fixed, so ensure you have that many...

**Comment by kijai** [comment]
Video length - 1 frame must be dividable by 4, that's literally what it means, you have to make sure the frames actually passed fit that requirement. 

The example setup should work with the example video as it can get the 101 frames (which works because 100 can be divided by 4), when selecting every 3th like the loader  does there, but videos shorter than that wouldn't have enough frames, and you will end up with different amount that might not fit the requirement. 

So you will have to adjust the loader to ensure the frame count.

**Comment by cr7Por** [comment]
hahaha, i think someone take this as Video length-1, which is not, it means Video length minus 1

**Comment by neopiccolorat** [comment]
> Video length - 1 frame must be dividable by 4, that's literally what it means, you have to make sure the frames actually passed fit that requirement.

What does that even mean? You realize that people using these tools are not devs?
Someone loads any video, the default is frame_load_cap 101, and select_every_nth 3
I would assume that it would load max the first 101 frames, and then use 1 frame every 3 frames.

So it should work with any video length since there someone is deciding how many frames are used. Maybe work on the tool so it does it automatically?

Don't take it the wrong way but there is no reason to complicate things like that, have weird error and respond with : It says what it says.

**Comment by neopiccolorat** [comment]
> hahaha, i think someone take this as Video length-1, which is not, it means Video length minus 1

how does it help the person who originally posted the problem, thanks for not helping

**Comment by cr7Por** [comment]
> > hahaha, i think someone take this as Video length-1, which is not, it means Video length minus 1
> 
> how does it help the person who originally posted the problem, thanks for not helping

ensure that frames number meet the requirement i think. let us say you have a video of 91 frames, and select_every_nth 3 will give you 30 frames, but 30 - 1 = 29 is not dividable by 4, while 29 frame - 1=28  is.

so i think you should set frame_load_cap to 29x3= 87

**Comment by shaun-ba** [comment]
I don't understand this at all...

HyVideoSampler
`video_length - 1 (that's minus one frame)` must be a multiple of 4, got 40

**Comment by shaun-ba** [comment]
> Hope this helps someone... I was having the same issue with the clip multiple of 4s, but minus 1. I was able to drop the sample video I was wanting to use into Davinci Resolve. On the "Cut" screen, I right clicked on the "Change Clip Duration". Selected format of "Frames" and in this case changed it to 121. (i.e. 121 -1 = 120... 120/4 = 30). Then rendered on the "Deliver" Screen. Then used the new rendered video as the example video

changing the length manually shouldn't make a difference because the loader only loads the number of frames you set? Also the last step I don't think is right, 120/4 shouldn't it be 120/3 ends up with a number divisible by 4?

I don't know, but i guess you are the one who got it working.
