### ISSUE TITLE
DownloadAndLoadHyVideoTextEncoder expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by ringodotnl** [kijai/ComfyUI-HunyuanVideoWrapper#148]
Error:

DownloadAndLoadHyVideoTextEncoder expected str, bytes or os.PathLike object, not NoneType

On windows 11 with Cuda 12.4 and portable comfyui version

Log:

Loading text encoder model (clipL) from: C:\apps\ComfyUI_Windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: C:\apps\ComfyUI_Windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
!!! Exception during processing !!! expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 617, in loadmodel
    text_encoder_2 = TextEncoder(
                     ^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 169, in __init__
    self.tokenizer, self.tokenizer_path = load_tokenizer(
                                          ^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 71, in load_tokenizer
    tokenizer = CLIPTokenizer.from_pretrained(tokenizer_path, max_length=77)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2032, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2272, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\apps\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\transformers\models\clip\tokenization_clip.py", line 312, in __init__
    with open(merges_file, encoding="utf-8") as merges_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not NoneType

Any idea?

**Comment by CambridgeComputing** [comment]
Can you share your workflow? It's not 100% clear in these errors, but you might be missing your CLIP model.

**Comment by kijai** [comment]
Missing model files from the clip model. You can also set that to disabled and connect any clip_l model to the text encoder using the normal comfy Load clip.
