### ISSUE TITLE
HyVideoModelLoader - module 'folder_paths' has no attribute 'get_full_path_or_raise'

### ISSUE THREAD

**Issue by Raphinirt** [kijai/ComfyUI-HunyuanVideoWrapper#151]
Everytime i try to Queue Prompt, this error appears.

```
2024-12-15 13:15:07,722 - root - INFO - got prompt
2024-12-15 13:15:09,203 - root - ERROR - !!! Exception during processing !!! module 'folder_paths' has no attribute 'get_full_path_or_raise'
2024-12-15 13:15:09,205 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 283, in loadmodel
    model_path = folder_paths.get_full_path_or_raise("diffusion_models", model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'folder_paths' has no attribute 'get_full_path_or_raise'
```

**Comment by kijai** [comment]
You need to update your ComfyUI itself.

**Comment by Raphinirt** [comment]
> You need to update your ComfyUI itself.

I did update it with the manager but that did not work. It worked after i updated it with the update_comfyui.bat file.
Thanks for the quick reply!
