### ISSUE TITLE
Cannot copy out of meta tensor;

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [kijai/ComfyUI-HunyuanVideoWrapper#152]
I have selected forchao_fp6 with bf16 weight. and I got this error.

Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

got prompt
model_type FLOW
Scheduler config: FrozenDict({'num_train_timesteps': 1000, 'shift': 9.0, 'reverse': True, 'solver': 'euler', 'n_tokens': None, '_use_default_values': ['num_train_timesteps', 'n_tokens']})
Quantizing model with <function _get_linear_subclass_inserter.<locals>.insert_subclass at 0x00000262B1DA7E20>
Requested to load HyVideoModel
!!! Exception during processing !!! Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 428, in loadmodel
    comfy.model_management.load_models_gpu([patcher])
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 515, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 334, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 363, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 758, in partially_load
    self.detach()
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 767, in detach
    self.unpatch_model(self.offload_device, unpatch_weights=unpatch_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\model_patcher.py", line 670, in unpatch_model
    self.model.to(device_to)
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\pclif\AppData\Roaming\Python\Python312\site-packages\torch\nn\modules\module.py", line 1333, in convert
    raise NotImplementedError(
NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.

**Comment by Bocchi-Chan2023** [comment]
fp8 weight generates the same error.

**Comment by Bocchi-Chan2023** [comment]
nvm I found related issue

**Comment by NekomiSakura** [comment]
same error,could you tell me how did you fix it? ; (

**Comment by Boruga01** [comment]
same error

> same error,could you tell me how did you fix it? ; (

do you manage to fix it?
