### ISSUE TITLE
not downloading llama-transformers version LLM

### ISSUE THREAD

**Issue by perobueno** [kijai/ComfyUI-HunyuanVideoWrapper#157]
**I wanted to try the input image workflow added yesterday but it seems stuck in downloading the model:**
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\models\clip\clip-vit-large-patch14
Downloading model to: A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\models\LLM\llava-llama-3-8b-v1_1-transformers
A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\huggingface_hub\file_download.py:834: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
Fetching 13 files:   8%|████▉                                                           | 1/13 [00:00<00:03,  3.07it/s]

**Comment by perobueno** [comment]
Also after restarting because it got stuck, I get this:

Loading checkpoint shards:   0%|                                                                 | 0/4 [00:00<?, ?it/s]
!!! Exception during processing !!! No such file or directory: "A:\\COMFYUI_2\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM\\llava-llama-3-8b-v1_1-transformers\\model-00001-of-00004.safetensors"
Traceback (most recent call last):
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 642, in loadmodel
    text_encoder = TextEncoder(
                   ^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 167, in __init__
    self.model, self.model_path = load_text_encoder(
                                  ^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 46, in load_text_encoder
    text_encoder = LlavaForConditionalGeneration.from_pretrained(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\transformers\modeling_utils.py", line 4264, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\transformers\modeling_utils.py", line 4755, in _load_pretrained_model
    state_dict = load_state_dict(
                 ^^^^^^^^^^^^^^^^
  File "A:\COMFYUI_2\ComfyUI_windows_portable\venv\Lib\site-packages\transformers\modeling_utils.py", line 504, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: No such file or directory: "A:\\COMFYUI_2\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM\\llava-llama-3-8b-v1_1-transformers\\model-00001-of-00004.safetensors"

Prompt executed in 0.98 seconds

So I guess it assumes its downloaded already but of course it didn't download int he first place.

**Comment by perobueno** [comment]
okay It seems it WAS downloadeing stuff but it was so much it wasn't stuck probably... I guess I'll have to delete the folder and restart.
