### ISSUE TITLE
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。

### ISSUE THREAD

**Issue by shenyan-008** [kijai/ComfyUI-HunyuanVideoWrapper#166]
HyVideoPromptMixSampler
backend='inductor' raised:
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\.17068.16632.tmp' -> 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\173fbc68d2269ca1806ce503e0401162736c1a67c2303c42f9b0701d8782b8f5'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
import torch._dynamo
torch._dynamo.config.suppress_errors = True

FETCH DATA from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Loading text encoder model (clipL) from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\models\clip\clip-vit-large-patch14
Loading text encoder model (llm) from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:06<00:00,  1.73s/it]
Text encoder to dtype: torch.float16
Loading tokenizer (llm) from: C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
llm prompt attention_mask shape: torch.Size([1, 161]), masked tokens: 30
clipL prompt attention_mask shape: torch.Size([1, 77]), masked tokens: 31
llm prompt attention_mask shape: torch.Size([1, 161]), masked tokens: 31
clipL prompt attention_mask shape: torch.Size([1, 77]), masked tokens: 32
model_type FLOW
Scheduler config: FrozenDict({'num_train_timesteps': 1000, 'shift': 9.0, 'reverse': True, 'solver': 'euler', 'n_tokens': None, '_use_default_values': ['n_tokens', 'num_train_timesteps']})
Using accelerate to load and assign model weights to device...
Requested to load HyVideoModel
loaded completely 9.5367431640625e+25 12555.953247070312 True
Input (height, width, video_length) = (480, 720, 65)
Sampling 65 frames in 17 latents at 720x480 with 20 inference steps
  0%|                                                                                           | 0/20 [00:01<?, ?it/s]
!!! Exception during processing !!! backend='inductor' raised:
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\.17068.16632.tmp' -> 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\173fbc68d2269ca1806ce503e0401162736c1a67c2303c42f9b0701d8782b8f5'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Traceback (most recent call last):
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\output_graph.py", line 1446, in _call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\repro\after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\__init__.py", line 2234, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1521, in compile_fx
    return aot_autograd(
           ^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\backends\common.py", line 72, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_functorch\aot_autograd.py", line 1071, in aot_module_simplified
    compiled_fn = dispatch_and_compile()
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_functorch\aot_autograd.py", line 1056, in dispatch_and_compile
    compiled_fn, _ = create_aot_dispatcher_function(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_functorch\aot_autograd.py", line 522, in create_aot_dispatcher_function
    return _create_aot_dispatcher_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_functorch\aot_autograd.py", line 759, in _create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
                               ^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_functorch\_aot_autograd\jit_compile_runtime_wrappers.py", line 179, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1350, in fw_compiler_base
    return _fw_compiler_base(model, example_inputs, is_inference)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 1359, in _fw_compiler_base
    _recursive_joint_graph_passes(model)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\compile_fx.py", line 281, in _recursive_joint_graph_passes
    joint_graph_passes(gm)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\fx_passes\joint_graph.py", line 460, in joint_graph_passes
    count += patterns.apply(graph.graph)  # type: ignore[arg-type]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\pattern_matcher.py", line 1729, in apply
    if is_match(m) and entry.extra_check(m):
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\pattern_matcher.py", line 1331, in check_fn
    if is_match(specific_pattern_match) and extra_check(specific_pattern_match):
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 146, in should_pad_addmm
    return should_pad_common(mat1, mat2, input) and should_pad_bench(
                                                    ^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 567, in should_pad_bench
    set_cached_base_mm_benchmark_time(ori_time_key, ori_time)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\fx_passes\pad_mm.py", line 262, in set_cached_base_mm_benchmark_time
    return get_pad_cache().set_value(key, value=value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 286, in set_value
    self.update_local_cache(cache)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 257, in update_local_cache
    write_atomic(
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_inductor\codecache.py", line 466, in write_atomic
    tmp_path.rename(path)
  File "pathlib.py", line 1363, in rename
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\.17068.16632.tmp' -> 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\173fbc68d2269ca1806ce503e0401162736c1a67c2303c42f9b0701d8782b8f5'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes_rf_inversion.py", line 613, in process
    noise_pred = transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 748, in forward
    img, txt = block(*double_block_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 465, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1269, in __call__
    return self._torchdynamo_orig_callable(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 1064, in __call__
    result = self._inner_convert(
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 526, in __call__
    return _compile(
           ^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 924, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 666, in compile_inner
    return _compile_inner(code, one_graph, hooks, transform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_utils_internal.py", line 87, in wrapper_function
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 699, in _compile_inner
    out_code = transform_code_object(code, transform)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\bytecode_transformation.py", line 1322, in transform_code_object
    transformations(instructions, code_options)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 219, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 634, in transform
    tracer.run()
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 2796, in run
    super().run()
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 983, in run
    while self.step():
          ^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 895, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 580, in wrapper
    return handle_graph_break(self, inst, speculation.reason)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\symbolic_convert.py", line 649, in handle_graph_break
    self.output.compile_subgraph(self, reason=reason)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\output_graph.py", line 1142, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\output_graph.py", line 1369, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\output_graph.py", line 1416, in call_user_compiler
    return self._call_user_compiler(gm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\D\ComfyUI_HunYuanVideo\ComfyUI_windows_0.3\python_embeded\Lib\site-packages\torch\_dynamo\output_graph.py", line 1465, in _call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\.17068.16632.tmp' -> 'C:\\Users\\2696v3\\AppData\\Local\\Temp\\torchinductor_2696v3\\cache\\173fbc68d2269ca1806ce503e0401162736c1a67c2303c42f9b0701d8782b8f5'

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

**Comment by aidenli** [comment]
同问，mark一下

**Comment by morganavr** [comment]
+1, I have the same error when trying to use "HunyuanVideo Torch Compile Settings" node.
```
FileExistsError: [WinError 183] Cannot create a file when that file already exists
```

If I change `dynamic`  to `true` - I've got a different error:
```
HyVideoSampler
backend='inductor' raised:
CompilationError: at 8:11:
def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
xnumel = 56623104
xoffset = tl.program_id(0) * XBLOCK
xindex = xoffset + tl.arange(0, XBLOCK)[:]
xmask = tl.full([XBLOCK], True, tl.int1)
x0 = xindex
tmp0 = tl.load(in_ptr0 + (x0), None)
tmp1 = tmp0.to(tl.float32)


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
import torch._dynamo
torch._dynamo.config.suppress_errors = True

**Comment by Onkitova** [comment]
setting dynamic to true worked for me, btw, thanks

**Comment by runtimecai** [comment]
In the previous node, setting dynamic to true was helpful for me. By the way, thank you
