### ISSUE TITLE
!!! Exception during processing !!! "replication_pad3d_cuda" not implemented for 'BFloat16'

### ISSUE THREAD

**Issue by francksitb** [kijai/ComfyUI-HunyuanVideoWrapper#180]
Error after rendering in the HunyuanVideo Decode node:

!!! Exception during processing !!! "replication_pad3d_cuda" not implemented for 'BFloat16'
Traceback (most recent call last):
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 1236, in decode
    video = vae.decode(
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\diffusers\utils\accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 345, in decode
    decoded = self._decode(z).sample
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 312, in _decode
    return self.spatial_tiled_decode(z, return_dict=return_dict)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\autoencoder_kl_causal_3d.py", line 462, in spatial_tiled_decode
    decoded = self.decoder(tile)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\vae.py", line 251, in forward
    sample = self.conv_in(sample)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Franck\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\vae\unet_causal_3d_blocks.py", line 77, in forward
    x = F.pad(x, self.time_causal_padding, mode=self.pad_mode)
RuntimeError: "replication_pad3d_cuda" not implemented for 'BFloat16'

**Comment by francksitb** [comment]
Found a solution, by using fp16 in stead of bf16 in the vaeloader.

**Comment by CodeAlexx** [comment]
> Found a solution, by using fp16 in stead of bf16 in the vaeloader.

where is this fp16 version?

**Comment by francksitb** [comment]
> > Found a solution, by using fp16 in stead of bf16 in the vaeloader.
> 
> where is this fp16 version?

![image](https://github.com/user-attachments/assets/449ffa82-bafb-4572-abaa-44b0d4e97015)

**Comment by CodeAlexx** [comment]
thank you

**Comment by mdkberry** [comment]
still didnt work for my potato 3060 12GB VRam I now get 

VAEDecodeTiled 'AutoencoderKLCausal3D' object has no attribute 'spacial_compression_decode'

**Comment by ariexietrotiv** [comment]
Where can I get that fp16?
Thank you

**Comment by mdkberry** [comment]
most of my problems were solved by upgrading torch in my portable version of comfyui using [this method](https://github.com/comfyanonymous/ComfyUI/issues/5111#issuecomment-2383750853)  once I upgraded it was fixed, but I had done a few other tweaks along the way so they might have helped:

I'd had problems with "Comfyui flow control" node that needed to be un-installed because it was stopping my comfyui seeing anything other than gguf models (couldnt see safetensors). and I had to switch some load nodes out for others that worked. 

after both the above the VAE decoder stopped giving me problems.

**Comment by ariexietrotiv** [comment]
tHANK you
