### ISSUE TITLE
Regarding the issue of the HunyuanVideo TextEncode node not matching the node demonstrated in the presentation.

### ISSUE THREAD

**Issue by Ninth-Dawn** [kijai/ComfyUI-HunyuanVideoWrapper#181]
Hello, I noticed that the HunyuanVideo TextEncode node I’m using is not the same as the one displayed by the team on the main page. Moreover, in the workflow I’ve set up—which is identical to the one on the main page—the HunyuanVideo TextEncode node won’t run and shows the following error. Do you have any suggestions for a solution?

got prompt
!!! Exception during processing !!! list index out of range
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 796, in process
    prompt_embeds, negative_prompt_embeds, attention_mask, negative_attention_mask = encode_prompt(self,
                                                                                     ^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 721, in encode_prompt
    text_inputs = text_encoder.text2tokens(prompt,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 253, in text2tokens
    text_tokens = self.processor(
                  ^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\models\llava\processing_llava.py", line 145, in __call__
    image_inputs = self.image_processor(images, **output_kwargs["images_kwargs"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\image_processing_utils.py", line 41, in __call__
    return self.preprocess(images, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\models\clip\image_processing_clip.py", line 286, in preprocess
    images = make_list_of_images(images)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\image_utils.py", line 185, in make_list_of_images
    if is_batched(images):
       ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\image_utils.py", line 158, in is_batched
    return is_valid_image(img[0])
                          ~~~^^^
IndexError: list index out of range

Prompt executed in 0.01 seconds
![5@}}2K8~ K}`{YDFEZ`42KG](https://github.com/user-attachments/assets/99658087-95b3-424e-b307-2e9e1f2bdeef)

**Comment by kijai** [comment]
The full xtuner model is meant to be used with the IP2V encoder node, for the normal text encoder node you'd want to use the other one.

**Comment by Ninth-Dawn** [comment]
Thank you, I got it running

**Comment by tankenyuen-ola** [comment]
I have used the IP2V encoder node but still the same issue occurred, unsure how to solve this issue.
<img width="1357" alt="Screenshot 2025-01-14 at 9 59 08 AM" src="https://github.com/user-attachments/assets/67d40fed-3497-401f-82b9-a638784e9003" />

**Comment by kijai** [comment]
> I have used the IP2V encoder node but still the same issue occurred, unsure how to solve this issue.
> <img width="1357" alt="Screenshot 2025-01-14 at 9 59 08 AM" src="https://github.com/user-attachments/assets/67d40fed-3497-401f-82b9-a638784e9003" />
> 
> 

But you didn't give it any image, that node reads an image and uses it as part of the prompt.

**Comment by tankenyuen-ola** [comment]
Ohh I thought that it supports input without images, anyway I solved the issue by installing another llm model thus it works, thanks!
