### ISSUE TITLE
ip2v_example flow fails

### ISSUE THREAD

**Issue by kaosbeat** [kijai/ComfyUI-HunyuanVideoWrapper#213]
Trying the Image Prompt 2 Video workflow.
Llava downloads fine, but upon the TextImageEncode (IP2V) node the workflow stops with an "`invalid Image Type`" exception
I'm using the supplied "`example_input.png`"

other hunyuan wrokflow examplers work fine
relevant part from the log:

```


2024-12-24T10:39:12.802361 - Prompt executed in 0.01 seconds
2024-12-24T10:42:13.828720 - got prompt
2024-12-24T10:42:13.846467 - !!! Exception during processing !!! Invalid image type. Expected either PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray, but got <class 'str'>.
2024-12-24T10:42:13.846690 - Traceback (most recent call last):
  File "/bigdata/AItools/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/bigdata/AItools/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/bigdata/AItools/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/bigdata/AItools/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/bigdata/AItools/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 823, in process
    prompt_embeds, negative_prompt_embeds, attention_mask, negative_attention_mask = encode_prompt(self,
  File "/bigdata/AItools/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 748, in encode_prompt
    text_inputs = text_encoder.text2tokens(prompt,
  File "/bigdata/AItools/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/text_encoder/__init__.py", line 253, in text2tokens
    text_tokens = self.processor(
  File "/home/kaos/.pyenv/versions/comfy/lib/python3.10/site-packages/transformers/models/llava/processing_llava.py", line 107, in __call__
    image_inputs = self.image_processor(images, return_tensors=return_tensors)
  File "/home/kaos/.pyenv/versions/comfy/lib/python3.10/site-packages/transformers/image_processing_utils.py", line 41, in __call__
    return self.preprocess(images, **kwargs)
  File "/home/kaos/.pyenv/versions/comfy/lib/python3.10/site-packages/transformers/models/clip/image_processing_clip.py", line 286, in preprocess
    images = make_list_of_images(images)
  File "/home/kaos/.pyenv/versions/comfy/lib/python3.10/site-packages/transformers/image_utils.py", line 205, in make_list_of_images
    raise ValueError(
ValueError: Invalid image type. Expected either PIL.Image.Image, numpy.ndarray, torch.Tensor, tf.Tensor or jax.ndarray, but got <class 'str'>.

2024-12-24T10:42:13.846893 - Prompt executed in 0.01 seconds
```

**Comment by kijai** [comment]
I believe you have to update transformers to get past that error.

**Comment by kaosbeat** [comment]
upgrading transformers from 4.44.2 > 4.47.1  indeed solved the issue
