### ISSUE TITLE
VAE decoding fails when num_frames is set to 1

### ISSUE THREAD

**Issue by Ulexer** [kijai/ComfyUI-HunyuanVideoWrapper#22]
```
got prompt
Input (height, width, video_length) = (320, 512, 1)
Sampling 1 frames in 1 latents at 512x320 with 2 inference steps
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:17<00:00,  8.50s/it]
Allocated memory: memory=11.847 GB
Max allocated memory: max_memory=12.451 GB
Max reserved memory: max_reserved=12.500 GB
!!! Exception during processing !!! permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 4
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 783, in decode
    video = video_processor.postprocess_video(video=video, output_type="pt")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\video_processor.py", line 102, in postprocess_video
    batch_vid = video[batch_idx].permute(1, 0, 2, 3)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 3 is not equal to len(dims) = 4
```
![Снимок экрана 2024-12-05 031223](https://github.com/user-attachments/assets/27db2c2f-c963-45cd-84c0-f4bcba4429ed)

**Comment by kijai** [comment]
Fixed.
