### ISSUE TITLE
keep missing the wrapper nodes no matter what i try (uninstal / fix etc)

### ISSUE THREAD

**Issue by eranmahalu** [kijai/ComfyUI-HunyuanVideoWrapper#228]
![image](https://github.com/user-attachments/assets/6e7146b4-04a7-4156-8a85-50addb790d06)

keep missing the wrapper nodes no matter what i try (uninstal / fix etc)

please help

**Comment by kijai** [comment]
As with every "missing node" you need to look into the startup log to see why it fails to import, it's almost always either missing or wrong version of some dependency. Look for "module not found" or similar errors, or share your log here.

**Comment by ianaxelbay** [comment]
Please help! same issue here, log:
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-29 10:34:32.477431
** Platform: Windows
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI_windows_portable\comfyui.log

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.9 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32697 MB
pytorch version: 2.0.1+cu118
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
python_executable_path:  D:\ComfyUI_windows_portable\python_embeded\python.exe
python_embeded_path:  D:\ComfyUI_windows_portable\python_embeded
D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchvision\datapoints\__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torchvision\transforms\v2\__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 22, in <module>
    from ..modeling_utils import ModelMixin
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\auto.py", line 31, in <module>    from .torchao import TorchAoHfQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\torchao\__init__.py", line 15, in <module>
    from .torchao_quantizer import TorchAoHfQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\torchao\torchao_quantizer.py", line 57, in <module>
    torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\hunyuandit\pipeline_hunyuandit.py", line 26, in <module>
    from ...models import AutoencoderKL, HunyuanDiT2DModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper\__init__.py", line 1, in <module>
    from .run import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper\run.py", line 27, in <module>
    from .infer import Text2Image, Text2ImagePipelineLoad, Image2Views, Image2ViewsPipelineLoad, Removebg, Views2Mesh, \  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper\infer\__init__.py", line 25, in <module>
    from .text_to_image import Text2Image
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper\infer\text_to_image.py", line 26, in <module>
    from diffusers import HunyuanDiTPipeline, AutoPipelineForText2Image
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.hunyuandit.pipeline_hunyuandit because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper module for custom nodes: Failed to import diffusers.pipelines.hunyuandit.pipeline_hunyuandit because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS as NODES_CLASS, NODE_DISPLAY_NAME_MAPPINGS as NODES_DISPLAY
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 9, in <module>
    from .hyvideo.constants import PROMPT_TEMPLATE
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\constants.py", line 23, in <module>
    'fp8_e4m3fn': torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper module for custom nodes: module 'torch' has no attribute 'float8_e4m3fn'
### Loading: ComfyUI-Impact-Pack (V8.1.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.9.1)
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.10-10-ga618f768 | Released on '2024-12-29'
[SD Prompt Reader] Node version: 1.3.4
[SD Prompt Reader] Core version: 1.3.5
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\autoencoders\__init__.py", line 1, in <module>
    from .autoencoder_asym_kl import AsymmetricAutoencoderKL
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\autoencoders\autoencoder_asym_kl.py", line 22, in <module>
    from ..modeling_utils import ModelMixin
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\modeling_utils.py", line 35, in <module>
    from ..quantizers import DiffusersAutoQuantizer, DiffusersQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\__init__.py", line 15, in <module>
    from .auto import DiffusersAutoQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\auto.py", line 31, in <module>    from .torchao import TorchAoHfQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\torchao\__init__.py", line 15, in <module>
    from .torchao_quantizer import TorchAoHfQuantizer
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\quantizers\torchao\torchao_quantizer.py", line 57, in <module>
    torch.float8_e4m3fn,
AttributeError: module 'torch' has no attribute 'float8_e4m3fn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 920, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\pipelines\hunyuandit\pipeline_hunyuandit.py", line 26, in <module>
    from ...models import AutoencoderKL, HunyuanDiT2DModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2092, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX\__init__.py", line 1, in <module>
    from .node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX\node.py", line 36, in <module>
    from .infer import Removebg, Image2Views, Views2Mesh
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX\infer\__init__.py", line 25, in <module>
    from .text_to_image import Text2Image
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX\infer\text_to_image.py", line 26, in <module>
    from diffusers import HunyuanDiTPipeline, AutoPipelineForText2Image
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 911, in __getattr__
    value = getattr(module, name)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 910, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\utils\import_utils.py", line 922, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.pipelines.hunyuandit.pipeline_hunyuandit because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'

Cannot import D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX module for custom nodes: Failed to import diffusers.pipelines.hunyuandit.pipeline_hunyuandit because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
module 'torch' has no attribute 'float8_e4m3fn'
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 220 nodes successfully.

        "Art should disturb the comfortable and comfort the disturbed." - Cesar Cruz


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-upscale-by-model
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.5 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_Hunyuan3D_EX
   0.6 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UltraPixel
   1.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hunyuan3D-1-wrapper
   1.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json [DONE]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json [DONE]

**Comment by kijai** [comment]
> pytorch version: 2.0.1+cu118

This is extremely old version of pytorch, lots of things including these nodes require newer version, I recommend the latest 2.5.1+cu124.

To be honest as it's that old, probably best to re-install with latest ComfyUI.

**Comment by ianaxelbay** [comment]
> This is extremely old version of pytorch, lots of things including these nodes require newer version, I recommend the latest 2.5.1+cu124.
> To be honest as it's that old, probably best to re-install with latest ComfyUI.

Thanks! I managed to update it, but I had no luck. As you said, I had to reinstall it along with ComfyUI. Help was much appreciated!

**Comment by fresno808** [comment]
> > This is extremely old version of pytorch, lots of things including these nodes require newer version, I recommend the latest 2.5.1+cu124.
> > To be honest as it's that old, probably best to re-install with latest ComfyUI.
> 
> Thanks! I managed to update it, but I had no luck. As you said, I had to reinstall it along with ComfyUI. Help was much appreciated!

were you able to figure it out? Ive been stuck as fixing or uninstall/reinstall doesnt work.
