### ISSUE TITLE
IP2V error with bnb_nf4 quant with xtuner/llava-llama-3-8b-v1_1-transformers

### ISSUE THREAD

**Issue by charleschenf5** [kijai/ComfyUI-HunyuanVideoWrapper#229]
Running IP2V and setting text encoder to bnb_nf4 using xtuner/llava-llama-3-8b-v1_1-transformers errors with:

ValueError: The input provided to the model are wrong. The number of image tokens is 0 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.

Note:  bitsandbytes installed.  nf4 works fine with Kijai/llava-llama-3-8b-text-encoder-tokenizer

---

Loading tokenizer (vlm) from: \ComfyUI\models\LLM\llava-llama-3-8b-v1_1-transformers
!!! Exception during processing !!! The input provided to the model are wrong. The number of image tokens is 0 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.
Traceback (most recent call last):
  File "\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 823, in process
    prompt_embeds, negative_prompt_embeds, attention_mask, negative_attention_mask = encode_prompt(self,
                                                                                     ^^^^^^^^^^^^^^^^^^^
  File "\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 753, in encode_prompt
    prompt_outputs = text_encoder.encode(text_inputs,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 307, in encode
    outputs = self.model(
              ^^^^^^^^^^^
  File "\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\python_embeded\Lib\site-packages\transformers\models\llava\modeling_llava.py", line 492, in forward
    inputs_embeds, attention_mask, labels, position_ids = self._merge_input_ids_with_image_features(
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\python_embeded\Lib\site-packages\transformers\models\llava\modeling_llava.py", line 365, in _merge_input_ids_with_image_features
    raise ValueError(
ValueError: The input provided to the model are wrong. The number of image tokens is 0 while the number of image given to the model is 1. This prevents correct indexing and breaks batch generation.

**Comment by blkwll** [comment]
I think what I was missing when I got this error, was to include "<image>" somewhere in your description in the text input..

**Comment by kijai** [comment]
Yes indeed the prompt has to include an image token `<image>` for each of the image inputs used.

**Comment by charleschenf5** [comment]
That solved it.  Thank you!
