### ISSUE TITLE
Hunyuan Video Model Loader issues on M4 MacBook 

### ISSUE THREAD

**Issue by ncri** [kijai/ComfyUI-HunyuanVideoWrapper#231]
I run into the following issue with my M4 Max Macbook (128 GB RAM):

```shell
!!! Exception during processing !!! 'img_in.proj.weight'
Traceback (most recent call last):
  File "/Users/.../dev/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../dev/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../dev/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/.../dev/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../dev/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 307, in loadmodel
    set_module_tensor_to_device(transformer, name, device=transformer_load_device, dtype=dtype_to_use, value=sd[name])
                                                                                                             ~~^^^^^^
KeyError: 'img_in.proj.weight'
``` 

I used the following settings:

<img width="913" alt="Bildschirmfoto 2024-12-27 um 21 28 56" src="https://github.com/user-attachments/assets/4ee3286c-c220-46fa-83dc-6c4f134322c3" />

Any idea how to fix? I tried various other settings but always get this or another error.

**Comment by Slavrix** [comment]
im getting the same error running on windows
