### ISSUE TITLE
AttributeError: 'VAE' object has no attribute 'to'

### ISSUE THREAD

**Issue by neutrinotek** [kijai/ComfyUI-HunyuanVideoWrapper#241]
I've tried various model/vae combos (bf16/fp32) with these nodes, and cannot seem to get it to work. Every time I get through sampling and move to decoding, I get the following error:

```
!!! Exception during processing !!! 'VAE' object has no attribute 'to'

Traceback (most recent call last):

  File "/home/runner/ComfyUI/execution.py", line 328, in execute

    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/execution.py", line 203, in get_output_data

    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/execution.py", line 174, in _map_node_over_list

    process_inputs(input_dict, i)

  File "/home/runner/ComfyUI/execution.py", line 163, in process_inputs

    results.append(getattr(obj, func)(**inputs))

                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/runner/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 1440, in decode

    vae.to(device)

    ^^^^^^

AttributeError: 'VAE' object has no attribute 'to'

Prompt executed in 287.25 seconds

fatal: No names found, cannot describe anything.
```

Any thoughts? I'm using the models directly from the Kijai huggingface page, but the only way I can use Hunyuan currently are the Low-VRAM options which I can't use Enhance a Video with.

**Comment by elchupacabrinski** [comment]
did you find a solution? running into the same problem

**Comment by neutrinotek** [comment]
Yeah... Not sure if yours is the same issue, but mine was an oversight by me. I was using the standard "Load VAE" node instead of the HunyuanVideo VAE Loader.
