### ISSUE TITLE
Weir  artifact  out put

### ISSUE THREAD

**Issue by pondloso** [kijai/ComfyUI-HunyuanVideoWrapper#32]
![AnimateDiff_01220](https://github.com/user-attachments/assets/e1f59bcc-def8-4c22-97b8-58884968d7c7)

out put it all  black and white  artifact  
i use original workflow.
test with sag and sdpa out put it always black and white  artifact  video.

**Comment by protector131090** [comment]
![Uploading ezgif-1-6640b1a7b9.gif…]()
mine are like this

**Comment by protector131090** [comment]
Uploading HunyuanVideo_00013.mp4…

**Comment by pondloso** [comment]
I test with fresh install comfyui just  only for this ,it still give me same   black and white artifact out put.
this is really drive me nut. I have no idea what is wrong.

**Comment by kijai** [comment]
> I test with fresh install comfyui just  only for this ,it still give me same   black and white artifact out put.
> this is really drive me nut. I have no idea what is wrong.

Did you test with sdpa after latest update? Never seen anything close to that kind of output before, which GPU do you have?

**Comment by pondloso** [comment]
> > I test with fresh install comfyui just  only for this ,it still give me same   black and white artifact out put.
> > this is really drive me nut. I have no idea what is wrong.
> 
> Did you test with sdpa after latest update? Never seen anything close to that kind of output before, which GPU do you have?

my GPU is 4060 ti.

 with  sdpa  form our new update **"RuntimeError: CUDA error: out of memory"**
.......
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\_tensor_str.py", line 339, in _tensor_str
    self = self.float()
           ^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

FETCH DATA from: F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

my GPU is 4060 ti.
........................................


Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [00:20<00:00,  5.22s/it]
Text encoder to dtype: torch.float16
Loading tokenizer (llm) from: F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
prompt attention_mask:  torch.Size([1, 161])
prompt attention_mask:  torch.Size([1, 77])
Using accelerate to load and assign model weights to device...
Scheduler config: FrozenDict({'num_train_timesteps': 1000, 'shift': 9.0, 'reverse': True, 'solver': 'euler', 'n_tokens': None, '_use_default_values': ['n_tokens', 'num_train_timesteps']})
Input (height, width, video_length) = (320, 320, 33)
Swapping 20 double blocks and 0 single blocks
Sampling 33 frames in 9 latents at 320x320 with 20 inference steps
  0%|                                                                                           | 0/20 [00:59<?, ?it/s]
Exception in thread Thread-11 (prompt_worker):
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 694, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 537, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 692, in forward
    block.to(self.offload_device, non_blocking=True)
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1340, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 900, in _apply
    module._apply(fn)
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 927, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1326, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\main.py", line 126, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 501, in execute
    result, error, ex = execute(self.server, dynamic_prompt, self.caches, node_id, extra_data, executed, prompt_id, execution_list, pending_subgraph_results)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 391, in execute
    input_data_formatted[name] = [format_value(x) for x in inputs]
                                  ^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\execution.py", line 243, in format_value
    return str(x)
           ^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\_tensor.py", line 523, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\_tensor_str.py", line 708, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\_tensor_str.py", line 625, in _str_intern
    tensor_str = _tensor_str(self, indent)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable_hyunvideo\python_embeded\Lib\site-packages\torch\_tensor_str.py", line 339, in _tensor_str
    self = self.float()
           ^^^^^^^^^^^^
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

FETCH DATA from: F:\ComfyUI_windows_portable_hyunvideo\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by kijai** [comment]
It's really hard to tell without any errors yeah, with the block_swapping it's normal that it uses both VRAM and RAM, you could try disable the block swap (disconnect that node) with even lower resolution just to see if it works at all.

**Comment by pondloso** [comment]
I came back to tell that i made it all work  both sdpa and sag.
I'm not sure what it the reason but i most suspect it model file.

before this i try every thing install new comfy just for this. like 4-5 time but still not work

but this morning i just want another fight.

so i fresh install comfy again  but this time i want everything new.
so i download all of model again from huggingface.

i had no hope at all but out put come out beautiful like a miracle lol.

so i most suspect my model file that i download from first day some how is corrupted but it load and gen video but out put just artifact.

or maybe bacuse of our god kijai doing another god touch with udate some how trick my pc to stop being idoit.

Thank you for hard work god kijai .

about triton is very easy to install for me(after you had micro soft tool install)
