### ISSUE TITLE
Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (S:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\__init__.py)

### ISSUE THREAD

**Issue by protector131090** [kijai/ComfyUI-HunyuanVideoWrapper#34]
got prompt
!!! Exception during processing !!! Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (S:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\__init__.py)
Traceback (most recent call last):
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 129, in loadmodel
    from sageattention import sageattn_varlen
ImportError: cannot import name 'sageattn_varlen' from 'sageattention' (S:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 131, in loadmodel
    raise ValueError(f"Can't import SageAttention: {str(e)}")
ValueError: Can't import SageAttention: cannot import name 'sageattn_varlen' from 'sageattention' (S:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\__init__.py)

**Comment by protector131090** [comment]
sdpa works.

**Comment by rrroddri** [comment]
I had the same error with sageattention installed, you need to update to CUDA 12.5

**Comment by protector131090** [comment]
> I had the same error with sageattention installed, you need to update to CUDA 12.5

does it affect quality or speed only? how is itr diferent from sdpa?

**Comment by SyntaxDiffusion1** [comment]
im using cuda 12.50- sage attn works fine for cog and mochi. getting the same error

**Comment by rrroddri** [comment]
I'm sorry what helped me what uninstall sageattention and installing it again

**Comment by HASAN3DG** [comment]
> I'm sorry what helped me what uninstall sageattention and installing it again

Thank you, it helped. But if you could give us a simple way to delete it, because I deleted it and installed it again and it did not work.

**Comment by rrroddri** [comment]
activate your virtualenv
pip uninstall sageattention
pip install sageattention

**Comment by kijai** [comment]
I did manage to finally get sdpa working properly, anyone struggling with sage can try that instead, it will be slower of course.

**Comment by HASAN3DG** [comment]
> I did manage to finally get sdpa working properly, anyone struggling with sage can try that instead, it will be slower of course.

You are awesome man and you are serving humanity who are yearning for progress in an amazing way thank you :)

**Comment by selectai255** [comment]
for anybody else with this error i just had to update sage_attn    from python embedded folder
 python.exe -m  pip install --upgrade sage_attn

**Comment by alexeynimvideo** [comment]
still get it, looking for solution

**Comment by RakanishuFoo** [comment]
if anyone is still having this issue, I deleted all folders labeled sageattention in \ComfyUI_windows_portable\python_embeded\Lib\site-packages and then reinstalled sageattention and it worked for me

**Comment by zpengcom** [comment]
windows portable :  `python_embeded\python.exe -m pip install --upgrade sageattention`
sageattention 1.0.6 useful to me ~~（pytorch version: 2.5.1+cu124）~~
