### ISSUE TITLE
Error when running the v2v example workflow: HyVideoSampler  `video_length-1` must be a multiple of 4, got 40

### ISSUE THREAD

**Issue by git523** [kijai/ComfyUI-HunyuanVideoWrapper#40]
I got this error message (`video_length-1` must be a multiple of 4, got 46) using my 46-frame input video. So I set the "frame_load_cap" to 40 in the "Load Video" node, and still got this error message.

2024-12-05T14:55:26.495954 - Prompt executed in 6.56 seconds
2024-12-05T14:55:41.873285 - got prompt
2024-12-05T14:55:47.751729 - encoded latents shape2024-12-05T14:55:47.751729 -  2024-12-05T14:55:47.751729 - torch.Size([1, 16, 10, 56, 96])2024-12-05T14:55:47.751729 - 
2024-12-05T14:55:47.899975 - !!! Exception during processing !!! `video_length-1` must be a multiple of 4, got 40
2024-12-05T14:55:47.899975 - Traceback (most recent call last):
  File "D:\AI\2.ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\2.ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\2.ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\2.ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\2.ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 657, in process
    raise ValueError(
ValueError: `video_length-1` must be a multiple of 4, got 40

2024-12-05T14:55:47.900977 - Prompt executed in 5.93 seconds

**Comment by kijai** [comment]
> I got this error message (`video_length-1` must be a multiple of 4, got 46) using my 46-frame input video. So I set the "frame_load_cap" to 40 in the "Load Video" node, and still got this error message.

Like the error says, it's `video length - 1` that needs to be divisible by 4. So 45 would work for example.

**Comment by git523** [comment]
Oops, my bad, I changed it to 45 and now it is working! Thank you so much Kijai!

**Comment by SoftologyPro** [comment]
Could this be auto-set for videos that do not have a frame rate divisble by 4?  Crop the last 1-3 frames as necessary?
Otherwise the user needs to use some editing software to trim the videos themselves?
