### ISSUE TITLE
[ERROR] IndexError: index 30 is out of bounds for dimension 0 with size 30. [help!]

### ISSUE THREAD

**Issue by xhwSkhizein** [kijai/ComfyUI-HunyuanVideoWrapper#43]
i got an error when trying to use text2vid pipeline.

```
2024-12-05T18:23:31.256808 - Traceback (most recent call last):
  File "/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 692, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/comfyui/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 565, in __call__
    latents = self.scheduler.step(
              ^^^^^^^^^^^^^^^^^^^^
  File "/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/schedulers/scheduling_flow_match_discrete.py", line 240, in step
    dt = self.sigmas[self.step_index + 1] - self.sigmas[self.step_index]
         ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: index 30 is out of bounds for dimension 0 with size 30
```

**Comment by adamreading** [comment]
I get something similar when trying to run a second pass. It always works fine the first time the workflow is run - but the second time I get this !!! Exception during processing !!! index 31 is out of bounds for dimension 0 with size 31
Traceback (most recent call last):
  File "/data/app/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/app/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/app/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data/app/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data/app/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 822, in process
    out_latents = model["pipe"](
  File "/data/miniconda3/pkgs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data/app/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 600, in __call__
    latents = self.scheduler.step(
  File "/data/app/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/schedulers/scheduling_flow_match_discrete.py", line 240, in step
    dt = self.sigmas[self.step_index + 1] - self.sigmas[self.step_index]
IndexError: index 31 is out of bounds for dimension 0 with size 31

Prompt executed in 107.11 seconds
