### ISSUE TITLE
RuntimeError: PassManager::run failed

### ISSUE THREAD

**Issue by wangwenqiao666** [kijai/ComfyUI-HunyuanVideoWrapper#45]
!!! Exception during processing !!! PassManager::run failed
Traceback (most recent call last):
  File "/data/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/ComfyUI/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/data/ComfyUI/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 694, in process
    out_latents = model["pipe"](
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/diffusion/pipelines/pipeline_hunyuan_video.py", line 537, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/modules/models.py", line 689, in forward
    img, txt = block(*double_block_args)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/modules/models.py", line 205, in forward
    attn = attention(
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/modules/attention.py", line 129, in attention
    x = sageattn_varlen_func(
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/data/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/modules/attention.py", line 23, in sageattn_varlen_func
    return sageattn_varlen(q, k, v, cu_seqlens_q, cu_seqlens_kv, max_seqlen_q, max_seqlen_kv)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/sageattention/core.py", line 203, in sageattn_varlen
    o = attn_false_varlen(q_int8, k_int8, v, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, q_scale, k_scale, cu_seqlens_q_scale, cu_seqlens_k_scale, output_dtype=dtype)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/sageattention/attn_qk_int8_block_varlen.py", line 119, in forward
    _attn_fwd[grid](
  File "<string>", line 63, in _attn_fwd
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/triton/compiler/compiler.py", line 476, in compile
    next_module = compile_kernel(module)
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/triton/compiler/compiler.py", line 383, in <lambda>
    lambda src: optimize_ttgir(ttir_to_ttgir(src, num_warps), num_stages, arch))
  File "/home/pc/miniconda3/envs/comfyui/lib/python3.10/site-packages/triton/compiler/compiler.py", line 91, in optimize_ttgir
    pm.run(mod)
RuntimeError: PassManager::run failed
----------------------------------------------------------------------------------------------------------------
What's wrong?

**Comment by saiwen42** [comment]
Me too! Does anyone know how to solve this? Thanks a lot

**Comment by kijai** [comment]
It's an issue with sageattention install, which is complicated to troubleshoot. You can alternatively use sdpa as attention_mode now to avoid that.

**Comment by wangwenqiao666** [comment]
> It's an issue with sageattention install, which is complicated to troubleshoot. You can alternatively use sdpa as attention_mode now to avoid that.

Could you tell me how to modify it?

**Comment by saiwen42** [comment]
> > 这是 sageattention 安装的问题，排除故障很复杂。现在您也可以使用 sdpa 作为 Attention_mode 来避免这种情况。
> 
> 你能告诉我如何修改它吗？

<img width="371" alt="image" src="https://github.com/user-attachments/assets/52bd0186-ff1c-4e42-beea-23a4598eaa20">
