### ISSUE TITLE
Torchao doesn't work

### ISSUE THREAD

**Issue by rkfg** [kijai/ComfyUI-HunyuanVideoWrapper#59]
I'm not sure if it's an issue with torchao, my hardware not supporting the required CUDA version, some setup issues, or something else entirely. Running on Debian testing, 3090 Ti, 565.57.01, CUDA 12.4, torch 2.5.1+cu124, torchao 0.6.1+cu124, python 3.10.

Running with `torchao_int4` results in this:
```
comfyui-1  | 2024-12-07T11:02:42.569348046Z Using accelerate to load and assign model weights to device...
comfyui-1  | 2024-12-07T11:02:46.791543438Z !!! Exception during processing !!! AffineQuantizedTensor dispatch: attempting to run unimplemented operator/function: func=<OpOverload(op='aten._has_compatible_shallow_copy_type', overload='default')>, types=(<class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>,), arg_types=(<class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>, <class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>), kwarg_types={}
comfyui-1  | 2024-12-07T11:02:46.791584202Z Traceback (most recent call last):
comfyui-1  | 2024-12-07T11:02:46.791605056Z   File "/app/execution.py", line 323, in execute
comfyui-1  | 2024-12-07T11:02:46.791606445Z     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
comfyui-1  | 2024-12-07T11:02:46.791607472Z   File "/app/execution.py", line 198, in get_output_data
comfyui-1  | 2024-12-07T11:02:46.791608763Z     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
comfyui-1  | 2024-12-07T11:02:46.791609629Z   File "/app/execution.py", line 169, in _map_node_over_list
comfyui-1  | 2024-12-07T11:02:46.791610379Z     process_inputs(input_dict, i)
comfyui-1  | 2024-12-07T11:02:46.791612519Z   File "/app/execution.py", line 158, in process_inputs
comfyui-1  | 2024-12-07T11:02:46.791613284Z     results.append(getattr(obj, func)(**inputs))
comfyui-1  | 2024-12-07T11:02:46.791614129Z   File "/app/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 243, in loadmodel
comfyui-1  | 2024-12-07T11:02:46.791615049Z     quantize_(transformer, quant_func, device=device)
comfyui-1  | 2024-12-07T11:02:46.791615812Z   File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_api.py", line 468, in quantize_
comfyui-1  | 2024-12-07T11:02:46.791616665Z     _replace_with_custom_fn_if_matches_filter(
comfyui-1  | 2024-12-07T11:02:46.791617420Z   File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_api.py", line 208, in _replace_with_custom_fn_if_matches_filter
comfyui-1  | 2024-12-07T11:02:46.791618263Z     new_child = _replace_with_custom_fn_if_matches_filter(
comfyui-1  | 2024-12-07T11:02:46.791619032Z   File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_api.py", line 208, in _replace_with_custom_fn_if_matches_filter
comfyui-1  | 2024-12-07T11:02:46.791619842Z     new_child = _replace_with_custom_fn_if_matches_filter(
comfyui-1  | 2024-12-07T11:02:46.791620670Z   File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_api.py", line 208, in _replace_with_custom_fn_if_matches_filter
comfyui-1  | 2024-12-07T11:02:46.791621835Z     new_child = _replace_with_custom_fn_if_matches_filter(
comfyui-1  | 2024-12-07T11:02:46.791622615Z   File "/usr/local/lib/python3.10/dist-packages/torchao/quantization/quant_api.py", line 214, in _replace_with_custom_fn_if_matches_filter
comfyui-1  | 2024-12-07T11:02:46.791623442Z     model.to(device=device)  # move parent module to device
comfyui-1  | 2024-12-07T11:02:46.791624181Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1340, in to
comfyui-1  | 2024-12-07T11:02:46.791624999Z     return self._apply(convert)
comfyui-1  | 2024-12-07T11:02:46.791626023Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 900, in _apply
comfyui-1  | 2024-12-07T11:02:46.791626837Z     module._apply(fn)
comfyui-1  | 2024-12-07T11:02:46.791627962Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 928, in _apply
comfyui-1  | 2024-12-07T11:02:46.791628777Z     p_should_use_set_data = compute_should_use_set_data(param, param_applied)
comfyui-1  | 2024-12-07T11:02:46.791629541Z   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 903, in compute_should_use_set_data
comfyui-1  | 2024-12-07T11:02:46.791633367Z     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
comfyui-1  | 2024-12-07T11:02:46.791634162Z   File "/usr/local/lib/python3.10/dist-packages/torchao/utils.py", line 377, in _dispatch__torch_function__
comfyui-1  | 2024-12-07T11:02:46.791635005Z     return func(*args, **kwargs)
comfyui-1  | 2024-12-07T11:02:46.791635715Z   File "/usr/local/lib/python3.10/dist-packages/torchao/utils.py", line 393, in _dispatch__torch_dispatch__
comfyui-1  | 2024-12-07T11:02:46.791636529Z     raise NotImplementedError(f"{cls.__name__} dispatch: attempting to run unimplemented operator/function: {func=}, {types=}, {arg_types=}, {kwarg_types=}")
comfyui-1  | 2024-12-07T11:02:46.791637522Z NotImplementedError: AffineQuantizedTensor dispatch: attempting to run unimplemented operator/function: func=<OpOverload(op='aten._has_compatible_shallow_copy_type', overload='default')>, types=(<class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>,), arg_types=(<class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>, <class 'torchao.dtypes.affine_quantized_tensor.AffineQuantizedTensor'>), kwarg_types={}
comfyui-1  | 2024-12-07T11:02:46.791638954Z 
comfyui-1  | 2024-12-07T11:02:46.792026046Z Prompt executed in 4.28 seconds
```
Using int8dq produces a little different error: `NotImplementedError: LinearActivationQuantizedTensor dispatch: attempting to run unimplemented operator/function: func=<OpOverload(op='aten._has_compatible_shallow_copy_type', overload='default')>, types=(<class 'torchao.quantization.linear_activation_quantized_tensor.LinearActivationQuantizedTensor'>,), arg_types=(<class 'torchao.quantization.linear_activation_quantized_tensor.LinearActivationQuantizedTensor'>, <class 'torchao.quantization.linear_activation_quantized_tensor.LinearActivationQuantizedTensor'>), kwarg_types={}`

I see that the AO developers added something related to these functions in 0.6.1 but either it's a different issue or it's something with my own setup. I can run `fp8_e4m3fn` just fine, the `_fast` variant doesn't work due to my hardware CUDA level being too low (series 40 needed for that) so no questions here.

**Comment by Wurzeldieb** [comment]
I have the same problem and the same error, torchao_fp6 works wth CogvideoX 1.5 for me, but not here

**Comment by kijai** [comment]
I have never been able to figure this out, after quantization with torchao the model can not be moved from device to device or you get that error. With Cog it's fine as it gets so small that it can reside in VRAM all the time, with this it would need to be offloaded to have enough VRAM for decoding, which will also result in this same error.

**Comment by rkfg** [comment]
Thanks for the explanation! So it loads the 8-bit quantized model, expands it to 16 bit, then tries to quantize down with torch ao and OOMs? At least that's what I got when using the main device in the loader node. Would it be possible to maybe load it block by block, quantize with AO, unload the original weights and repeat? I don't know the internals, just a shot in the dark.

**Comment by kijai** [comment]
> Thanks for the explanation! So it loads the 8-bit quantized model, expands it to 16 bit, then tries to quantize down with torch ao and OOMs? At least that's what I got when using the main device in the loader node. Would it be possible to maybe load it block by block, quantize with AO, unload the original weights and repeat? I don't know the internals, just a shot in the dark.

You would want to use the original bf16 weights to load, I now changed the code to load and quant each block one by one with torchao directly on GPU, this goes through sampling fine but then I don't have the VRAM to decode. Could save the latents and do it separately for testing if the quality is worth it though.

**Comment by gghuanhuan** [comment]
Have you solved it? I also have the same problem

**Comment by nirurin** [comment]
Was there ever a resolution for this issue?

**Comment by rkfg** [comment]
I switched to a native workflow and GGUF with MultiGPU to swap layers, I don't think Torchao is worth the hassle.
