### ISSUE TITLE
Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by evanmathis** [kijai/ComfyUI-HunyuanVideoWrapper#62]
I've already re-downloaded the clips patch14, but now I'm running into this when trying to run the sample workflow:

```
got prompt
Loading text encoder model (clipL) from: /home/three5/Apps/COMFY/ComfyUI/models/clip/clip-vit-large-patch14
!!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
Traceback (most recent call last):
  File "/home/three5/Apps/COMFY/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/three5/Apps/COMFY/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/three5/Apps/COMFY/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/three5/Apps/COMFY/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/three5/Apps/COMFY/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 415, in loadmodel
    text_encoder_2 = TextEncoder(
  File "/home/three5/Apps/COMFY/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/text_encoder/__init__.py", line 184, in __init__
    self.model, self.model_path = load_text_encoder(
  File "/home/three5/Apps/COMFY/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/text_encoder/__init__.py", line 34, in load_text_encoder
    text_encoder = CLIPTextModel.from_pretrained(text_encoder_path)
  File "/home/three5/Apps/COMFY/ComfyUI/venv/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3994, in from_pretrained
    with safe_open(resolved_archive_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge
```
Any ideas what might be causing this?

Let me know if I can provide more info.

**Comment by kijai** [comment]
`Error while deserializing header: HeaderTooLarge` usually means there's a corrupt file, probably unfinished download or something.

**Comment by evanmathis** [comment]
Yeah that's what i was able to search up elsewhere but thought I'd ask here.  I've already tried re-downloading all of the models...

I'll try again.

Thanks!

**Comment by ctf05** [comment]
I got this error too. It was because I was git cloning the models. You need git's lts system for this to actually work. I fixed it by wget'ing the models and individual files instead.
