### ISSUE TITLE
显卡2080ti魔改的,不能玩该项目吗?RuntimeError: `ptxas` failed with error code 4294967295:

### ISSUE THREAD

**Issue by logo66612** [kijai/ComfyUI-HunyuanVideoWrapper#63]
2024-12-08 03:56:12.600] !!! Exception during processing !!! `ptxas` failed with error code 4294967295: 

[2024-12-08 03:56:12.604] Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\compiler.py", line 298, in make_cubin
    subprocess.run(ptxas_cmd, check=True, close_fds=False, stderr=flog)
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v12.5\\bin\\ptxas.exe', '-lineinfo', '-v', '--gpu-name=sm_75', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp6vgpvwxn.ptx', '-o', 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmp6vgpvwxn.ptx.o']' returned non-zero exit status 4294967295.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 737, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 571, in __call__
    noise_pred = self.transformer(  # For an input image (129, 192, 336) (1, 256, 256)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 735, in forward
    img, txt = block(*double_block_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\models.py", line 205, in forward
    attn = attention(
           ^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\attention.py", line 162, in attention
    x = sageattn_varlen_func(
        ^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\eval_frame.py", line 632, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\modules\attention.py", line 23, in sageattn_varlen_func
    return sageattn_varlen(q, k, v, cu_seqlens_q, cu_seqlens_kv, max_seqlen_q, max_seqlen_kv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\core.py", line 198, in sageattn_varlen
    q_int8, q_scale, k_int8, k_scale, cu_seqlens_q_scale, cu_seqlens_k_scale = per_block_int8_varlen(q, k, cu_seqlens_q, cu_seqlens_k, max_seqlen_q, max_seqlen_k, sm_scale=sm_scale)
                                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sageattention\quant_per_block_varlen.py", line 69, in per_block_int8
    quant_per_block_int8_kernel[grid](
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 662, in run
    kernel = self.compile(
             ^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\compiler\compiler.py", line 286, in compile
    next_module = compile_ir(module, metadata)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\compiler.py", line 332, in <lambda>
    stages["cubin"] = lambda src, metadata: self.make_cubin(src, metadata, options, self.capability)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\nvidia\compiler.py", line 312, in make_cubin
    raise RuntimeError(f'`ptxas` failed with error code {e.returncode}: \n{log}')
RuntimeError: `ptxas` failed with error code 4294967295:

**Comment by logo66612** [comment]
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: D:\AI\ComfyUI_windows_portable\comfyui.log
Comfy Pets is up to date.
Total VRAM 22528 MB, total RAM 32601 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\AI\ComfyUI_windows_portable\ComfyUI\web
NumExpr defaulting to 16 threads.
PATH BASENAME <function basename at 0x000002BC5AA15080>

**Comment by viryaka** [comment]
我的2080ti 也是，好像是因为2080ti 的Compute Capability 为 7.5（sm_75），属于 Turing 架构。这意味着它不支持 Compute Capability 8.0 及以上所引入的 bf16 特性。

**Comment by logo66612** [comment]
> 我的2080ti 也是，好像是因为2080ti 的Compute Capability 为 7.5（sm_75），属于 Turing 架构。这意味着它不支持 Compute Capability 8.0 及以上所引入的 bf16 特性。

谢谢,我查了下也是这么个意思,我被哪些UP给带偏了,他们之说显存多少多少G就能玩

**Comment by peterzhu9999** [comment]
我是2080ti魔改22G。可以跑通，之前报错不能用BF16，我就改成fp32或者fp16。但是视频分辨率480P就会爆显存。只能生成320P的。你这个报错我没遇到过。

**Comment by Anopoke** [comment]
我也是这个问题，请问你解决了吗？

**Comment by Anopoke** [comment]
我已经解决了，这是我的文章[unsloth报错RuntimeError: ptxas failed with error code 4294967295:](https://blog.csdn.net/m0_60495479/article/details/145984644)

**Comment by zslefour** [comment]
> 我已经解决了，这是我的文章[unsloth报错RuntimeError： ptxas failed with error code 4294967295：](https://blog.csdn.net/m0_60495479/article/details/145984644)

看了你的文章，我的cuda本来就是12.4，只是pytorch是2.5.1，我明天升级到2.6.0看看能不能解决。

**Comment by zslefour** [comment]
> 可以，都试试

从错误信息中发现，不管base_precision选择bf16还是fp16，到了Sampler还是要求bf16，而2080ti不支持bf16，看来是无解.

--------------错误信息------------------------------
ptxas C:\Users...\AppData\Local\Temp\tmpumohz431.ptx, line 387; error : Feature '.bf16' requires .target sm_80 or higher
ptxas C:\Users...\AppData\Local\Temp\tmpumohz431.ptx, line 387; error : Feature 'cvt with .f32.bf16' requires .target sm_80 or higher
.........
!!! Exception during processing !!! ptxas failed with error code 4294967295
