### ISSUE TITLE
Cannot import ....\custom_nodes\ComfyUI-HunyuanVideoWrapper module for custom nodes: f-string: unmatched '[' (nodes.py, line 502)

### ISSUE THREAD

**Issue by osagem** [kijai/ComfyUI-HunyuanVideoWrapper#70]
Cannot import:
log:
`[ComfyUI-Easy-Use] web root: K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 502
    "custom_prompt_template": ("STRING", {"default": f"{PROMPT_TEMPLATE['dit-llm-encode-video']["template"]}", "multiline": True}),
                                                                                                 ^^^^^^^^
SyntaxError: f-string: unmatched '['

Cannot import K:\AI\comfylAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper module for custom nodes: f-string: unmatched '[' (nodes.py, line 502)`

**open file ComfyUI-HunyuanVideoWrapper\nodes.py, line 502:**
`            "custom_prompt_template": ("STRING", {"default": f"{PROMPT_TEMPLATE['dit-llm-encode-video']["template"]}", "multiline": True}),
`
**replace to:**
`            "custom_prompt_template": ("STRING", {"default": f"{PROMPT_TEMPLATE['dit-llm-encode-video']['template']}", "multiline": True}),
`

**done
import OK**

**Comment by kijai** [comment]
Already been fixed.
