### ISSUE TITLE
No module named 'transformers.models.chameleon.configuration_chameleon

### ISSUE THREAD

**Issue by thistleknot** [kijai/ComfyUI-HunyuanVideoWrapper#71]
```

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: /home/user/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
[]
[]
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/home/user/ComfyUI/server.py", line 563, in get_object_info
    out[x] = node_info(x)
  File "/home/user/ComfyUI/server.py", line 530, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/home/user/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 467, in INPUT_TYPES
    file_list = [f for f in os.listdir(font_dir) if os.path.isfile(os.path.join(font_dir, f)) and f.lower().endswith(".ttf")]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fonts/truetype'

got prompt
The config attributes {'mid_block_causal_attn': True} were passed to AutoencoderKLCausal3D, but are not expected and will be ignored. Please verify your config.json configuration file.
Loading text encoder model (clipL) from: /home/user/ComfyUI/models/clip/clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: /home/user/ComfyUI/models/clip/clip-vit-large-patch14
Loading text encoder model (llm) from: /home/user/ComfyUI/models/LLM/llava-llama-3-8b-text-encoder-tokenizer
!!! Exception during processing !!! Failed to import transformers.models.chameleon.configuration_chameleon because of the following error (look up to see its traceback):
No module named 'transformers.models.chameleon.configuration_chameleon'
Traceback (most recent call last):
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module
  File "/home/user/miniconda3/envs/textgen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers.models.chameleon.configuration_chameleon'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/ComfyUI/execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user/ComfyUI/execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/user/ComfyUI/execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/user/ComfyUI/execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/nodes.py", line 476, in loadmodel
    text_encoder = TextEncoder(
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/text_encoder/__init__.py", line 156, in __init__
    self.model, self.model_path = load_text_encoder(
  File "/home/user/ComfyUI/custom_nodes/ComfyUI-HunyuanVideoWrapper/hyvideo/text_encoder/__init__.py", line 38, in load_text_encoder
    text_encoder = AutoModel.from_pretrained(
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 543, in from_pretrained
    # Set the adapter kwargs
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 780, in keys
    if key in self._config_mapping.keys()
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 781, in <listcomp>
    ]
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 777, in _load_attr_from_module
    self._load_attr_from_module(key, self._model_mapping[key]),
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 693, in getattribute_from_module
    # object at the top level.
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
  File "/home/user/comfy/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
RuntimeError: Failed to import transformers.models.chameleon.configuration_chameleon because of the following error (look up to see its traceback):
No module named 'transformers.models.chameleon.configuration_chameleon'

Prompt executed in 1.77 seconds
```

No module named 'transformers.models.chameleon.configuration_chameleon

**Comment by kijai** [comment]
Probably need to update `transformers`

**Comment by thistleknot** [comment]
I was having some type of competing packages... but worked around the issue by updating all and then selecting just this package for update, this can be closed.
