### ISSUE TITLE
RuntimeError: The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 4

### ISSUE THREAD

**Issue by Xardous** [kijai/ComfyUI-HunyuanVideoWrapper#73]
Keep getting this while trying to generate, i see it has something to do with the resolution of the video (v2v) but i can never get the two tensor sizes to match. 

Full code:
`got prompt
encoded latents shape torch.Size([1, 16, 26, 96, 96])
Input (height, width, video_length) = (512, 512, 13)
tensor([978.2609, 972.9730, 967.2897, 961.1651, 954.5454, 947.3684, 939.5604, 931.0344, 921.6867, 911.3924, 900.0000, 887.3240, 873.1343, 857.1429, 838.9830, 818.1818, 794.1176, 765.9575, 732.5581, 692.3077, 642.8571, 580.6452, 500.0001, 391.3044, 236.8421], device='cuda:0')
!!! Exception during processing !!! The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 4
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 822, in process
    out_latents = model["pipe"](
                  ^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 487, in __call__
    latents, timesteps = self.prepare_latents(
                         ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\diffusion\pipelines\pipeline_hunyuan_video.py", line 219, in prepare_latents
    latents = latents * (1 - latent_timestep / 1000) + latent_timestep / 1000 * noise
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (96) must match the size of tensor b (64) at non-singleton dimension 4`




Specs:
4090
i9-12900k
32gb ddr4

Would appreciate any help,
Thanks

**Comment by selectai255** [comment]
don't know what the error means but heres a couple of tips,   make sure your input video is the same resolution as the resolution you are generating and make sure the number of frames of your source video you input is the same as you are generating , so according to above you should resize source video to 512x512 and load frame cap at 13 

hope this helps   actually 13 frames might be a bad number i think it should be multiple of 8 plus 1 try 17
