### ISSUE TITLE
Can't use bnb_n4f: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models.

### ISSUE THREAD

**Issue by JamesIV4** [kijai/ComfyUI-HunyuanVideoWrapper#84]
Hey there, I have the latest version of bitsandbytes installed, but the bnb_nf4 option still doesn't work for me. I haven't seen anyone else mentioning this issue yet.

I'm on Windows 11, 2060 12 GB VRAM, 16 GB system RAM.
Python 3.11.4
PyTorch version: 2.1.0+cu121
CUDA 12.5
triton 3.1.0
sageattention 1.0.6
flash-attn NOT WORKING (could that be the cause of this?)

I've let the flash-attn install go for a very long time (hours) and it never finished. I also tried compiling from the flash attention repository, but it also hung there. I can't identify the correct wheel prebuilt for my partiocular setup, and building one seems to be having an issue.

That might not be related to the nf4 stuff working though.

Without nf4, the text encoder works, it just takes a very long time.

Here's the full log output:
```
FETCH DATA from: S:\Repos\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
Loading text encoder model (clipL) from: S:\Repos\ComfyUI\ComfyUI\models\clip\clip-vit-large-patch14
Text encoder to dtype: torch.float16
Loading tokenizer (clipL) from: S:\Repos\ComfyUI\ComfyUI\models\clip\clip-vit-large-patch14
S:\Repos\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Loading text encoder model (llm) from: S:\Repos\ComfyUI\ComfyUI\models\LLM\llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 4/4 [01:01<00:00, 15.50s/it]
!!! Exception during processing !!! `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
Traceback (most recent call last):
  File "S:\Repos\ComfyUI\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\Repos\ComfyUI\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 477, in loadmodel
    text_encoder = TextEncoder(
                   ^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 156, in __init__
    self.model, self.model_path = load_text_encoder(
                                  ^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\hyvideo\text_encoder\__init__.py", line 38, in load_text_encoder
    text_encoder = AutoModel.from_pretrained(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 564, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\Repos\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 4015, in from_pretrained
    dispatch_model(model, **device_map_kwargs)
  File "S:\Repos\ComfyUI\python_embeded\Lib\site-packages\accelerate\big_modeling.py", line 498, in dispatch_model
    model.to(device)
  File "S:\Repos\ComfyUI\python_embeded\Lib\site-packages\transformers\modeling_utils.py", line 2861, in to
    raise ValueError(
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.

```

Using the latest version of the low vram workflow (as of 45 minutes ago):
```
{
  "last_node_id": 40,
  "last_link_id": 45,
  "nodes": [
    {
      "id": 3,
      "type": "HyVideoSampler",
      "pos": [
        668,
        -62
      ],
      "size": [
        315,
        334
      ],
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "HYVIDEOMODEL",
          "link": 2
        },
        {
          "name": "hyvid_embeds",
          "type": "HYVIDEMBEDS",
          "link": 36
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": null,
          "shape": 7
        },
        {
          "name": "stg_args",
          "type": "STGARGS",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "links": [
            4
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoSampler"
      },
      "widgets_values": [
        512,
        512,
        33,
        20,
        6,
        9,
        2,
        "fixed",
        1,
        1
      ]
    },
    {
      "id": 35,
      "type": "HyVideoBlockSwap",
      "pos": [
        -351,
        -44
      ],
      "size": [
        315,
        130
      ],
      "flags": {},
      "order": 0,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "block_swap_args",
          "type": "BLOCKSWAPARGS",
          "links": [
            43
          ]
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoBlockSwap"
      },
      "widgets_values": [
        20,
        0,
        true,
        true
      ]
    },
    {
      "id": 36,
      "type": "Note",
      "pos": [
        -140,
        600
      ],
      "size": [
        262.6133117675781,
        105.17330932617188
      ],
      "flags": {},
      "order": 1,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "bnb_nf4 requires bitsandbytes installed, it is necessary if you don't have VRAM to run the text encoding, it will not affect VRAM usage during video sampling"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 38,
      "type": "Note",
      "pos": [
        241.49647521972656,
        163.09042358398438
      ],
      "size": [
        313.94659423828125,
        76.57331085205078
      ],
      "flags": {},
      "order": 2,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "If you have sageattention working, use that for fastest sampling."
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 37,
      "type": "Note",
      "pos": [
        -321.4975280761719,
        -211.55799865722656
      ],
      "size": [
        262.6133117675781,
        105.17330932617188
      ],
      "flags": {},
      "order": 3,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "To further reduce VRAM usage, you can also enable swapping for up to 40 single blocks. More you swap, slower it gets though."
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 40,
      "type": "Note",
      "pos": [
        113.16300201416016,
        -577.575927734375
      ],
      "size": [
        262.6133117675781,
        105.17330932617188
      ],
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [],
      "outputs": [],
      "properties": {},
      "widgets_values": [
        "If you have working Triton installation, compilation can further reduce VRAM use, granted you can run the actual compilation process. To enable compilation, connect this to the model loader"
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 34,
      "type": "VHS_VideoCombine",
      "pos": [
        1367,
        -275
      ],
      "size": [
        371.7926940917969,
        310
      ],
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 42
        },
        {
          "name": "audio",
          "type": "AUDIO",
          "link": null,
          "shape": 7
        },
        {
          "name": "meta_batch",
          "type": "VHS_BatchManager",
          "link": null,
          "shape": 7
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "Filenames",
          "type": "VHS_FILENAMES",
          "links": null
        }
      ],
      "properties": {
        "Node name for S&R": "VHS_VideoCombine"
      },
      "widgets_values": {
        "frame_rate": 24,
        "loop_count": 0,
        "filename_prefix": "HunyuanVideo",
        "format": "video/h264-mp4",
        "pix_fmt": "yuv420p",
        "crf": 19,
        "save_metadata": true,
        "pingpong": false,
        "save_output": true,
        "videopreview": {
          "hidden": false,
          "paused": false,
          "params": {
            "filename": "HunyuanVideo_00059.mp4",
            "subfolder": "",
            "type": "temp",
            "format": "video/h264-mp4",
            "frame_rate": 16
          },
          "muted": false
        }
      }
    },
    {
      "id": 16,
      "type": "DownloadAndLoadHyVideoTextEncoder",
      "pos": [
        -300,
        380
      ],
      "size": [
        441,
        178
      ],
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "hyvid_text_encoder",
          "type": "HYVIDTEXTENCODER",
          "links": [
            35
          ]
        }
      ],
      "properties": {
        "Node name for S&R": "DownloadAndLoadHyVideoTextEncoder"
      },
      "widgets_values": [
        "Kijai/llava-llama-3-8b-text-encoder-tokenizer",
        "openai/clip-vit-large-patch14",
        "fp16",
        false,
        2,
        "bnb_nf4"
      ]
    },
    {
      "id": 39,
      "type": "HyVideoTorchCompileSettings",
      "pos": [
        -353.23699951171875,
        -576.843017578125
      ],
      "size": [
        441,
        274
      ],
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [],
      "outputs": [
        {
          "name": "torch_compile_args",
          "type": "COMPILEARGS",
          "links": [
            45
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoTorchCompileSettings"
      },
      "widgets_values": [
        "inductor",
        false,
        "default",
        false,
        64,
        true,
        true,
        true,
        true,
        true
      ]
    },
    {
      "id": 7,
      "type": "HyVideoVAELoader",
      "pos": [
        442,
        -282
      ],
      "size": [
        379.166748046875,
        82
      ],
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "compile_args",
          "type": "COMPILEARGS",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "vae",
          "type": "VAE",
          "links": [
            6
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoVAELoader"
      },
      "widgets_values": [
        "hunyuan_video_vae_bf16.safetensors",
        "bf16"
      ]
    },
    {
      "id": 1,
      "type": "HyVideoModelLoader",
      "pos": [
        24,
        -63
      ],
      "size": [
        509.7506103515625,
        178
      ],
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "compile_args",
          "type": "COMPILEARGS",
          "link": 45,
          "shape": 7
        },
        {
          "name": "block_swap_args",
          "type": "BLOCKSWAPARGS",
          "link": 43,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "model",
          "type": "HYVIDEOMODEL",
          "links": [
            2
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoModelLoader"
      },
      "widgets_values": [
        "hunyuan_video_720_cfgdistill_fp8_e4m3fn.safetensors",
        "bf16",
        "fp8_e4m3fn",
        "offload_device",
        "sageattn_varlen"
      ]
    },
    {
      "id": 5,
      "type": "HyVideoDecode",
      "pos": [
        924.3921508789062,
        -284.8564453125
      ],
      "size": [
        345.4285888671875,
        150
      ],
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "vae",
          "type": "VAE",
          "link": 6
        },
        {
          "name": "samples",
          "type": "LATENT",
          "link": 4
        }
      ],
      "outputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "links": [
            42
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoDecode"
      },
      "widgets_values": [
        true,
        64,
        128,
        false
      ]
    },
    {
      "id": 30,
      "type": "HyVideoTextEncode",
      "pos": [
        210,
        380
      ],
      "size": [
        400,
        200
      ],
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "text_encoders",
          "type": "HYVIDTEXTENCODER",
          "link": 35
        },
        {
          "name": "custom_prompt_template",
          "type": "PROMPT_TEMPLATE",
          "link": null,
          "shape": 7
        },
        {
          "name": "clip_l",
          "type": "CLIP",
          "link": null,
          "shape": 7
        }
      ],
      "outputs": [
        {
          "name": "hyvid_embeds",
          "type": "HYVIDEMBEDS",
          "links": [
            36
          ]
        }
      ],
      "properties": {
        "Node name for S&R": "HyVideoTextEncode"
      },
      "widgets_values": [
        "portrait shot video of a palm tree swaying in the wind",
        "bad quality video",
        "video"
      ]
    }
  ],
  "links": [
    [
      2,
      1,
      0,
      3,
      0,
      "HYVIDEOMODEL"
    ],
    [
      4,
      3,
      0,
      5,
      1,
      "LATENT"
    ],
    [
      6,
      7,
      0,
      5,
      0,
      "VAE"
    ],
    [
      35,
      16,
      0,
      30,
      0,
      "HYVIDTEXTENCODER"
    ],
    [
      36,
      30,
      0,
      3,
      1,
      "HYVIDEMBEDS"
    ],
    [
      42,
      5,
      0,
      34,
      0,
      "IMAGE"
    ],
    [
      43,
      35,
      0,
      1,
      1,
      "BLOCKSWAPARGS"
    ],
    [
      45,
      39,
      0,
      1,
      0,
      "COMPILEARGS"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "ds": {
      "scale": 0.9090909090909097,
      "offset": [
        341.40020226212033,
        373.4708616136263
      ]
    },
    "ue_links": []
  },
  "version": 0.4
}
```

**Comment by kijai** [comment]
Hmm, what version of `transformers` and `accelerate` do you have installed?

**Comment by JamesIV4** [comment]
I had `transformers` 4.44.0, and now installed 4.47.0, and for `accelerate` I have 1.2.0 (latest).

**Comment by CambridgeComputing** [comment]
I had the same issue and upgrading `transformers` to `4.47.0` seems to have resolved it.

**Comment by JamesIV4** [comment]
> I had the same issue and upgrading `transformers` to `4.47.0` seems to have resolved it.

Ah man, I was so hopeful, I just tried after updating `tranformers`, but no luck. I still have the same error.

**Comment by kijai** [comment]
I had `transformers `4.44.2 and had no issues, updated to 4.47.0 now and that also seems to work.

Similarly I had `bitsandbytes-0.44.1` which worked, updated to `bitsandbytes-0.45.0` now and also still works.

Not sure what else it can be, assuming you are on latest version of the nodes themselves.

**Comment by kijai** [comment]
I did just notice you have **very** old pytorch... would recommend updating that to 2.5.1+cu124 in general at this point.

**Comment by JamesIV4** [comment]
Wait, when I updated `transformers`, I used a normal terminal window and did `pip install -u transformers`, but looking at the console logs, ComfyUI is using an embedded version of python stored in the ComfyUI folders. I think I need to find a way to update THAT version.

**Comment by JamesIV4** [comment]
I'm switching ComfyUI to use my global packages, will update here.

**Comment by kijai** [comment]
> Wait, when I updated `transformers`, I used a normal terminal window and did `pip install -U transformers`, but looking at the console logs, ComfyUI is using an embedded version of python stored in the ComfyUI folders. I think I need to find a way to update THAT version.

Oh yeah indeed, for the portable you install pip packages by running this in the python_embeded - folder (for example):

`python.exe -m pip install -U transformers`

**Comment by JamesIV4** [comment]
> > Wait, when I updated `transformers`, I used a normal terminal window and did `pip install -U transformers`, but looking at the console logs, ComfyUI is using an embedded version of python stored in the ComfyUI folders. I think I need to find a way to update THAT version.
> 
> Oh yeah indeed, for the portable you install pip packages by running this in the python_embeded - folder (for example):
> 
> `python.exe -m pip install -U transformers`

YES that worked beautifully, thank you.
