### ISSUE TITLE
DownloadAndLoadHyVideoTextEncoder No package metadata was found for bitsandbytes

### ISSUE THREAD

**Issue by Bas667** [kijai/ComfyUI-HunyuanVideoWrapper#97]
The following problem: When I start the workflow, I get the following error message:

`DownloadAndLoadHyVideoTextEncoder No package metadata was found for bitsandbytes`

The download should actually start automatically. I then manually downloaded the folder “llava-llama-3-8b-text-encoder-tokenizer” from huggingface and packed it in /models/LLM/. But that doesn't help either.

Here is the complete log:

```
2024-12-10T11:21:12.872354 - got prompt
2024-12-10T11:21:12.909389 - !!! Exception during processing !!! No package metadata was found for bitsandbytes
2024-12-10T11:21:12.910391 - Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 563, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\StableDiffusion\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 434, in loadmodel
    quantization_config = BitsAndBytesConfig(
                          ^^^^^^^^^^^^^^^^^^^
  File "E:\StableDiffusion\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\quantization_config.py", line 402, in __init__
    self.post_init()
  File "E:\StableDiffusion\ComfyUI\python_embeded\Lib\site-packages\transformers\utils\quantization_config.py", line 460, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\metadata\__init__.py", line 1009, in version
  File "importlib\metadata\__init__.py", line 982, in distribution
  File "importlib\metadata\__init__.py", line 565, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes
```

**Comment by kijai** [comment]
The bnb_nf4 quantization option requires bitsandbytes library installed, I didn't want to make that automatic as that package sometimes has issues and is preferable to be installed manually.

For portable that can be done by running this command in the `ComfyUI_windows_portable\python_embeded` -folder:

`python.exe -m pip install bitsandbytes`

**Comment by Freamp** [comment]
You have to use:
`./python.exe -m pip install bitsandbytes`

**Comment by EdnilsonMonteiro** [comment]
I manually installed bitsandbytes. But now I'm getting this other error message.

DownloadAndLoadHyVideoTextEncoder
Failed to import transformers.models.timm_wrapper.configuration_timm_wrapper because of the following error (look up to see its traceback):
cannot import name 'ImageNetInfo' from 'timm.data' (C:\Users\edmon\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\timm\data\__init__.py)

**Comment by kijai** [comment]
> I manually installed bitsandbytes. But now I'm getting this other error message.
> 
> DownloadAndLoadHyVideoTextEncoder Failed to import transformers.models.timm_wrapper.configuration_timm_wrapper because of the following error (look up to see its traceback): cannot import name 'ImageNetInfo' from 'timm.data' (C:\Users\edmon\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\timm\data__init__.py)

Need to update `transformers `and/or `timm `as well.

**Comment by EdnilsonMonteiro** [comment]
Great, it worked for me. Thanks!

**Comment by parukapoor** [comment]
@kijai pls help where to update and hw? in the requirement.txt?

**Comment by CamooCodee** [comment]
I have the latest version (0.45.1) installed but I keep getting:

DownloadAndLoadHyVideoTextEncoder
Using `bitsandbytes` 4-bit quantization requires the latest version of bitsandbytes: `pip install -U bitsandbytes`

Any idea?

**Comment by FreezaSama** [comment]
> Great, it worked for me. Thanks!

can you say what exactly did you do please? I have the same issue

**Comment by yujiro85** [comment]
> > Great, it worked for me. Thanks!
> 
> can you say what exactly did you do please? I have the same issue

he probably updated timm version. At least that's what I did.
I navigated to comfyui/python_embedded/ directory (python.exe exists in here)
I checked my timm version by typing this:
python.exe -m pip show timm
which is an ancient version of 0.6.13
I upgraded it by typing this:
python.exe -s -m pip install "timm  >= 0.7"

Now the node works. Workflow doesn't work, I get another error from a different node, but this error doesn't exist anymore.

(You can also do the same thing for transformers, and as an additional info: I did upgraded my comfy's torch for no reason by typing python.exe -s -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124 if you do this, make sure you have cuda 12.4, I don't know if upgrading torch is needed to work hunyuan nodes, but I did)

**Comment by FreezaSama** [comment]
thank you so much. this worked!
